AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
Style/StringLiterals:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Layout/SpaceBeforeBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: space
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Naming/MethodParameterName:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Lint/EmptyBlock:
  Enabled: false
Lint/EmptyClass:
  Enabled: false
